# __main__.py
# This file is used to run the overall program.

# Import the required modules for password and request
from request import request_yes_or_no_input
from password import Password

# Define the main function used to run the program
def run_program():

  # Print welcome statement to the user
  print("\n\nWelcome to Python Password Generator\n")

  # Create a new instance of the Password class
  password: Password = Password()

  # Create infinite loop to keep generating new passwords until user requests to stop
  while True:

    # Print the new password generated by the password object
    print("\n\tYour new Password is: " + password.generate())

    # Ask the user if they want to generate another password
    input: str = request_yes_or_no_input(
        "\n\tWould you like to generate another password with the same settings? ")

    # If the user does not want to generate another password, break the infinite loop
    if (input == "no"):
      break

# If the file is being run directly, run the main function
if (__name__ == "__main__"):
  run_program()
